#!/bin/bash -eu
#
# Helper functions
#

if [ -e "${VARS:-}" ] ; then
	. "${VARS}"
fi

function out()
{
	local rc=$?

	trap - EXIT INT TERM HUP

	if [ "${rc}" -ne 0 ] ; then
		pr_error "Script failed"
	fi

	exit "${rc}"
}

function pr_error()
{
	echo -e "\e[31mError: ${*}\e[0m" >&2

}

function pr_info()
{
	echo -e "\e[33m${*}\e[0m"
}
