#!/bin/bash -eu
#
# Helper functions
#

if [ -e "${VARS:-}" ] ; then
	# shellcheck disable=SC1090
	. "${VARS}"
fi

function out()
{
	local rc=$?

	trap - EXIT INT TERM HUP

	if [ "${rc}" -ne 0 ] ; then
		pr_error "Script failed"
	fi

	exit "${rc}"
}

function pr_error()
{
	echo -e "\e[31mError: ${*}\e[0m" >&2

}

function pr_info()
{
	echo -e "\e[33m${*}\e[0m"
}

function partprobe_wait()
{
	local dev=${1} part=${2}
	local count

	partprobe -s "${dev}"

	count=0
	while [ ${count} -lt 10 ] ; do
		if [ -e "${part}" ] ; then
			return
		fi
		sleep .2
		count=$((count + 1))
	done

	pr_error "Timed out waiting for ${part}"
	return 1
}
