#!/bin/bash -eu
#
# Add user/group
#

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${0}")")"/../functions

if [ -z "${SUDO_USER:-}" ] || [ "${SUDO_USER}" = "ubuntu" ] ; then
	exit
fi

if grep -q "^${SUDO_USER}" "${MOUNT_POINT}"/etc/passwd ; then
	exit
fi

sudo_group=$(id -g "${SUDO_GID}" -n)
pr_info "Add group ${sudo_group}"
chroot "${MOUNT_POINT}" addgroup --gid "${SUDO_GID}" "${sudo_group}"

pr_info "Add user ${SUDO_USER}"
chroot "${MOUNT_POINT}" adduser --gid "${SUDO_GID}" --uid "${SUDO_UID}" \
       --gecos "" --disabled-password --no-create-home "${SUDO_USER}"

pr_info "Create etc/sudoers.d/${SUDO_USER}"
echo "${SUDO_USER} ALL = NOPASSWD: ALL" >"${MOUNT_POINT}"/etc/sudoers.d/"${SUDO_USER}"
chmod 440 "${MOUNT_POINT}"/etc/sudoers.d/"${SUDO_USER}"
