#!/bin/bash -eu
#
# Copy an image to an LV
#

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${0}")")"/../functions

pr_info "Copy image to ${LV_DEVICE}"
dd bs=10M if="${IMAGE}" of="${LV_DEVICE}" conv=sync status=progress

pr_info "Probe partitions of ${LV_DEVICE}"
partprobe -s "${LV_DEVICE}"
