#!/bin/bash -eu
#
# Relabel the filesystems on an LV
#

. "$(dirname "$(readlink -f "${0}")")"/../functions

pr_info "Re-label filesystems on ${LV_DEVICE}"
partprobe "${LV_DEVICE}"

for part in "${LV_DEVICE}"* ; do
	read -r label fstype < <(lsblk -n -f -o LABEL,FSTYPE "${part}")

	if [ -z "${label}" ] ; then
		# No label found
		continue
	fi

	# Reset label
	label=${label%-"${RELEASE}"}

	# Re-label
	case "${fstype}" in
		"")
			continue
			;;
		ext4)
			cmd=e2label
			;;
		vfat)
			cmd=vfatlabel
			;;
		*)
			pr_error "Unsupported label type: ${fstype}"
			exit 1
			;;
	esac
	"${cmd}" "${part}" "${label}-${RELEASE}"
done
