#!/bin/bash -eu
#
# Relabel the filesystems on an LV
#

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${0}")")"/../functions

pr_info "Relabel filesystems on ${LV_DEVICE}"
partprobe -s "${LV_DEVICE}"

for part in "${LV_DEVICE}"* ; do
	if [ "${part}" = "${LV_DEVICE}" ] ; then
		# Whole disk
		continue
	fi

	read -r label fstype < <(lsblk -n -o LABEL,FSTYPE "${part}")
	if [ -z "${label}" ] || [ -z "${fstype}" ] ; then
		# No label found
		continue
	fi

	new_label=
	case "${label}" in
		cloudimg-rootfs) new_label=${RELEASE}-root ;;
		UEFI)            new_label=${RELEASE^^}-UEFI ;;
		BOOT)            new_label=${RELEASE^^}-BOOT ;;
		"${RELEASE}"-*|"${RELEASE^^}"-*)
			# Already relabeled
			continue
			;;
		*)
			pr_error "Unsupported label name: ${label}"
			exit 1
			;;
	esac

	# Relabel
	case "${fstype}" in
		ext4) cmd=e2label ;;
		vfat) cmd=fatlabel ;;
		*)
			pr_error "Unsupported filesystem type: ${fstype}"
			exit 1
			;;
	esac
	"${cmd}" "${part}" "${new_label}"
done
